Imported Upstream version 2.8

diff --git a/mono/tests/Makefile.in b/mono/tests/Makefile.in
--- a/mono/tests/Makefile.in
+++ b/mono/tests/Makefile.in
@@ -51,10 +51,7 @@ CONFIG_HEADER = $(top_builddir)/config.h
 CONFIG_CLEAN_FILES = tests-config
 LTLIBRARIES = $(noinst_LTLIBRARIES)
 am__DEPENDENCIES_1 =
-@EGLIB_BUILD_FALSE@am__DEPENDENCIES_2 = $(am__DEPENDENCIES_1) \
-@EGLIB_BUILD_FALSE@	$(am__DEPENDENCIES_1)
-@EGLIB_BUILD_TRUE@am__DEPENDENCIES_2 = $(am__DEPENDENCIES_1)
-libtest_la_DEPENDENCIES = $(am__DEPENDENCIES_2)
+libtest_la_DEPENDENCIES = $(am__DEPENDENCIES_1)
 am_libtest_la_OBJECTS = libtest_la-libtest.lo
 libtest_la_OBJECTS = $(am_libtest_la_OBJECTS)
 libtest_la_LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) \
@@ -94,6 +91,7 @@ AUTOHEADER = @AUTOHEADER@
 AUTOMAKE = @AUTOMAKE@
 AWK = @AWK@
 BISON = @BISON@
+BOEHM_DEFINES = @BOEHM_DEFINES@
 BUILD_EXEEXT = @BUILD_EXEEXT@
 BUILD_GLIB_CFLAGS = @BUILD_GLIB_CFLAGS@
 BUILD_GLIB_LIBS = @BUILD_GLIB_LIBS@
@@ -135,7 +133,6 @@ GMODULE_LIBS = @GMODULE_LIBS@
 GMSGFMT = @GMSGFMT@
 GMSGFMT_015 = @GMSGFMT_015@
 GREP = @GREP@
-HAVE_BOEHM_GC = @HAVE_BOEHM_GC@
 HAVE_MSGFMT = @HAVE_MSGFMT@
 HOST_CC = @HOST_CC@
 INSTALL = @INSTALL@
@@ -167,6 +164,7 @@ MAINT = @MAINT@
 MAKEINFO = @MAKEINFO@
 MKDIR_P = @MKDIR_P@
 MONO_DL_NEED_USCORE = @MONO_DL_NEED_USCORE@
+MONO_NACL_ALIGN_MASK_OFF = @MONO_NACL_ALIGN_MASK_OFF@
 MSGFMT = @MSGFMT@
 MSGFMT_015 = @MSGFMT_015@
 MSGMERGE = @MSGMERGE@
@@ -189,6 +187,7 @@ PKG_CONFIG = @PKG_CONFIG@
 RANLIB = @RANLIB@
 SED = @SED@
 SET_MAKE = @SET_MAKE@
+SGEN_DEFINES = @SGEN_DEFINES@
 SHELL = @SHELL@
 SQLITE = @SQLITE@
 SQLITE3 = @SQLITE3@
@@ -226,7 +225,6 @@ datarootdir = @datarootdir@
 docdir = @docdir@
 docs_dir = @docs_dir@
 dvidir = @dvidir@
-eglib_dir = @eglib_dir@
 exec_prefix = @exec_prefix@
 export_ldflags = @export_ldflags@
 host = @host@
@@ -276,25 +274,21 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 SUBDIRS = cas assemblyresolve
-@EGLIB_BUILD_FALSE@glib_libs = $(GLIB_LIBS) $(GMODULE_LIBS)
-
-# avoid including eglib twice since GLIB_LIBS == GMODULE_LIBS for eglib builds
-@EGLIB_BUILD_TRUE@glib_libs = $(GLIB_LIBS)
 TEST_PROG = ../interpreter/mint
-JITTEST_PROG = ../mini/mono
+JITTEST_PROG = $(if $(VALGRIND), valgrind $(VALGRIND_ARGS),) $(if $(SGEN),$(top_builddir)/mono/mini/mono-sgen,$(top_builddir)/mono/mini/mono)
 TEST_PROG_RUN = MONO_SHARED_DIR=$(mono_build_root)/runtime MONO_CFG_DIR=$(mono_build_root)/runtime/etc $(LIBTOOL) --mode=execute $(TEST_PROG)
 JITTEST_PROG_RUN = MONO_SHARED_DIR=$(mono_build_root)/runtime MONO_CFG_DIR=$(mono_build_root)/runtime/etc $(LIBTOOL) --mode=execute $(JITTEST_PROG)
 RUNTIME_ARGS = --config tests-config --optimize=all --debug
 with_mono_path = MONO_PATH=$(mcs_topdir)/class/lib/net_2_0
-with_mono_path21 = MONO_PATH=$(mcs_topdir)/class/lib/net_2_1_raw
+with_mono_path_moonlight = MONO_PATH=$(mcs_topdir)/class/lib/moonlight_raw
 RUNTIME = $(with_mono_path) $(top_builddir)/runtime/mono-wrapper
-RUNTIME21 = $(with_mono_path21) $(top_builddir)/runtime/mono-wrapper
+RUNTIME_MOONLIGHT = $(with_mono_path_moonlight) $(top_builddir)/runtime/mono-wrapper
 MKBUNDLE = \
 	PKG_CONFIG_PATH=$(top_builddir):$(PKG_CONFIG_PATH) \
 	$(RUNTIME) $(mcs_topdir)/class/lib/net_2_0/mkbundle.exe
 
 MCS = $(RUNTIME) $(mcs_topdir)/class/lib/net_2_0/gmcs.exe -unsafe -nowarn:0162 -nowarn:0168 -nowarn:0219 -debug
-SMCS = $(RUNTIME21) --runtime=moonlight --security=temporary-smcs-hack $(mcs_topdir)/class/lib/net_2_1_raw/smcs.exe -unsafe -nowarn:0162 -nowarn:0168 -nowarn:0219
+SMCS = $(RUNTIME_MOONLIGHT) --runtime=moonlight --security=temporary-smcs-hack $(mcs_topdir)/class/lib/moonlight_raw/smcs.exe -unsafe -nowarn:0162 -nowarn:0168 -nowarn:0219
 ILASM = $(RUNTIME) $(mcs_topdir)/class/lib/net_2_0/ilasm.exe
 BENCHSRC = fib.cs random.cs nested-loops.cs ackermann.cs tight-loop.cs sieve.cs
 STRESS_TESTS_SRC = \
@@ -476,6 +470,13 @@ BASE_TEST_CS_SRC = \
 	async_read.cs		\
 	threadpool.cs		\
 	threadpool1.cs		\
+	threadpool-exceptions1.cs \
+	threadpool-exceptions2.cs \
+	threadpool-exceptions3.cs \
+	threadpool-exceptions4.cs \
+	threadpool-exceptions5.cs \
+	threadpool-exceptions6.cs \
+	threadpool-exceptions7.cs \
 	base-definition.cs	\
 	bug-27420.cs		\
 	bug-47295.cs		\
@@ -512,7 +513,6 @@ BASE_TEST_CS_SRC = \
 	exists.cs		\
 	handleref.cs	\
 	transparentproxy.cs \
-	imt_big_iface_test.cs \
 	dbnull-missing.cs	\
 	test-type-ctor.cs 	\
 	soft-float-tests.cs	\
@@ -622,10 +622,21 @@ BASE_TEST_CS_SRC = \
 	finalizer-wait.cs	\
 	critical-finalizers.cs	\
 	appdomain-thread-abort.cs \
+	xdomain-threads.cs	\
 	w32message.cs	\
 	bug-544446.cs	\
 	gc-altstack.cs	\
-	bug-599469.cs
+	large-gc-bitmap.cs	\
+	bug-561239.cs	\
+	bug-562150.cs	\
+	bug-575941.cs	\
+	bug-599469.cs	\
+	bug-389886-3.cs
+
+TEST_CS_SRC_DIST = \
+	$(BASE_TEST_CS_SRC)	\
+	async-exc-compilation.cs \
+	filter-stack.cs
 
 @AMD64_FALSE@@X86_FALSE@TEST_CS_SRC = $(BASE_TEST_CS_SRC) \
 @AMD64_FALSE@@X86_FALSE@	$(am__append_1)
@@ -634,19 +645,24 @@ BASE_TEST_CS_SRC = \
 @AMD64_FALSE@@X86_TRUE@	$(am__append_1)
 @AMD64_TRUE@TEST_CS_SRC = $(BASE_TEST_CS_SRC) async-exc-compilation.cs \
 @AMD64_TRUE@	$(am__append_1)
+@ARM_TRUE@PLATFORM_DISABLED_TESTS = filter-stack.exe
+@HOST_WIN32_TRUE@@X86_TRUE@PLATFORM_DISABLED_TESTS = async-exc-compilation.exe
 # bug #319249
 @IA64_TRUE@PLATFORM_DISABLED_TESTS = exception17.exe winx64structs.exe
-@PLATFORM_WIN32_TRUE@@X86_TRUE@PLATFORM_DISABLED_TESTS = async-exc-compilation.exe
 
 # bug #71274
 @POWERPC_TRUE@PLATFORM_DISABLED_TESTS = finalizer-abort.exe finalizer-exception.exe finalizer-exit.exe
 
 # The two finalizer tests only work under sgen
+# gc-altstack.exe fails under boehm because it has no support for altstack
+# bug-459094.exe creates an extremely deep directory tree
 DISABLED_TESTS = \
 	delegate-async-exception.exe	\
 	bug-348522.2.exe	\
 	finalizer-wait.exe	\
 	critical-finalizers.exe	\
+	gc-altstack.exe \
+	bug-459094.exe \
 	$(PLATFORM_DISABLED_TESTS)
 
 AOT_DISABLED_TESTS = constraints-load.exe
@@ -715,7 +731,10 @@ TEST_IL_SRC = \
 	bug-528055.il	\
 	constraints-load.il	\
 	array_load_exception.il \
-	bug-481403.il
+	bug-481403.il	\
+	interface-with-static-method.il	\
+	bug-515884.il	\
+	bug-633291.il
 
 
 #	bug-318677.il
@@ -734,35 +753,62 @@ TESTBS = $(BENCHSRC:.cs=.exe)
 STRESS_TESTS = $(STRESS_TESTS_SRC:.cs=.exe)
 
 # Generated tests for runtime invoke
-EXTRA_DIST = test-driver $(TEST_CS_SRC) $(TEST_IL_SRC) $(BENCHSRC) \
-	$(STRESS_TESTS_SRC) stress-runner.pl $(PREREQ_IL_SRC) \
-	$(PREREQ_CS_SRC) load-missing.il t-missing.cs \
-	load-exceptions.cs gen-runtime-invoke.cs \
+EXTRA_DIST = test-driver $(TEST_CS_SRC_DIST) $(TEST_IL_SRC) \
+	$(BENCHSRC) $(STRESS_TESTS_SRC) stress-runner.pl \
+	$(PREREQ_IL_SRC) $(PREREQ_CS_SRC) load-missing.il t-missing.cs \
+	load-exceptions.cs gen-runtime-invoke.cs make-imt-test.cs \
 	test-inline-call-stack-library.cs test-inline-call-stack.cs \
 	unhandled-exception-base-configuration.config \
 	unhandled-exception-legacy-configuration.config \
-	unhandled-exception-test-case.2.cs \
+	appdomain-unload.exe.config unhandled-exception-test-case.2.cs \
 	unhandled-exception-test-runner.2.cs bug-81673-interface.cs \
 	bug-81691-a.cs bug-81691-b.cs bug-81466-lib.il \
-	bug-324535-il.il make_imt_test.sh custom-modifiers.2.cs \
-	custom-modifiers-lib.il bug-382986-lib.cs coreclr-security.cs \
-	generic-unboxing.2.il generic-boxing.2.il generic-unbox.2.cs \
-	generic-box.2.cs generic-delegate2.2.cs \
-	generic-delegate2-lib.2.il async-exceptions.cs modules.cs \
-	modules-m1.cs
+	bug-324535-il.il custom-modifiers.2.cs custom-modifiers-lib.il \
+	bug-382986-lib.cs coreclr-security.cs generic-unboxing.2.il \
+	generic-boxing.2.il generic-unbox.2.cs generic-box.2.cs \
+	generic-delegate2.2.cs generic-delegate2-lib.2.il \
+	async-exceptions.cs modules.cs modules-m1.cs bug-438454.cs \
+	bug-438454.exe.stdout.expected
+GSHARED_TESTS = \
+		generics-sharing.2.exe shared-generic-methods.2.exe	\
+		shared-generic-synchronized.2.exe generic-initobj.2.exe		\
+		generics-sharing-other-exc.2.exe generic-box.2.exe		\
+		generic-unbox.2.exe generic-delegate.2.exe generic-sizeof.2.exe	\
+		generic-ldobj.2.exe generic-mkrefany.2.exe			\
+		generic-refanyval.2.exe generic-ldtoken.2.exe			\
+		generic-ldtoken-method.2.exe  generic-ldtoken-field.2.exe	\
+		generic-virtual.2.exe generic-tailcall.2.exe			\
+		generic-interface-methods.2.exe generic-array-type.2.exe	\
+		generic-method-patching.2.exe generic-static-methods.2.exe	\
+		generic-null-call.2.exe generic-tailcall2.2.exe			\
+		generic-array-exc.2.exe generic-special.2.exe			\
+		generic-exceptions.2.exe generic-delegate2.2.exe		\
+		generic-virtual2.2.exe generic-valuetype-interface.2.exe	\
+		generic-valuetype-newobj.2.exe generic-valuetype-newobj2.2.exe	\
+		generic-getgenericarguments.2.exe generic-type-builder.2.exe	\
+		generic-synchronized.2.exe generic-delegate-ctor.2.exe		\
+		generic-constrained.2.exe bug-431413.2.exe			\
+		generic-virtual-invoke.2.exe generic-typedef.2.exe		\
+		generic-marshalbyref.2.exe bug-459285.2.exe bug-461198.2.exe	\
+		generic-sealed-virtual.2.exe generic-system-arrays.2.exe	\
+		generic-stack-traces.2.exe generic-stack-traces2.2.exe		\
+		bug-472600.2.exe bug-473482.2.exe bug-473999.2.exe		\
+		bug-479763.2.exe generic-xdomain.2.exe				\
+		generic-type-load-exception.2.exe bug-616463.exe
+
 noinst_LTLIBRARIES = libtest.la
 INCLUDES = $(GLIB_CFLAGS) $(GMODULE_CFLAGS)
 
 # gcc-3.4.4 emits incorrect code when making indirect calls to stdcall functions using a tail call
 # This shows up when compiling mono_test_marshal_delegate ()
-@PLATFORM_WIN32_TRUE@libtest_la_CFLAGS = -fno-optimize-sibling-calls
-@PLATFORM_WIN32_FALSE@libtest_la_LDFLAGS = -rpath `pwd`
+@HOST_WIN32_TRUE@libtest_la_CFLAGS = -fno-optimize-sibling-calls
+@HOST_WIN32_FALSE@libtest_la_LDFLAGS = -rpath `pwd`
 # the exported names created by gcc for stdcall functions are missing the leading _, so MS.NET
 # can't find them. So we use --kill-at to remove the @ suffix as well.
-@PLATFORM_WIN32_TRUE@libtest_la_LDFLAGS = -no-undefined -rpath `pwd` -Wl,--kill-at
+@HOST_WIN32_TRUE@libtest_la_LDFLAGS = -no-undefined -rpath `pwd` -Wl,--kill-at
 libtest_la_SOURCES = libtest.c
-libtest_la_LIBADD = $(glib_libs)
-CLEANFILES = $(TESTSI_CS) $(TESTSI_IL) $(STRESS_TESTS) *.dll *.stdout *.exe stest.dat
+libtest_la_LIBADD = $(GLIB_LIBS)
+CLEANFILES = $(TESTSI_CS) $(TESTSI_IL) $(STRESS_TESTS) *.dll *.stdout *.aotlog *.exe stest.dat
 all: all-recursive
 
 .SUFFIXES:
@@ -1148,8 +1194,10 @@ aotcheck: testaot gshared-aot
 @POWERPC_TRUE@test_platform:	testbundle
 # Can't use mkbundle on win32 since there is no static build there
 # Can't run test-unhandled-exception on Windows because of all the debug popups...
-@PLATFORM_WIN32_TRUE@@POWERPC_FALSE@test_platform:
-@PLATFORM_WIN32_FALSE@@POWERPC_FALSE@test_platform:	testbundle test-iomap-regression
+@HOST_WIN32_TRUE@@POWERPC_FALSE@test_platform:
+# mkbundle uses the installed mono-2.pc so it won't work if there is no system mono
+#test_platform:	testbundle test-iomap-regression
+@HOST_WIN32_FALSE@@POWERPC_FALSE@test_platform:	test-iomap-regression
 
 #
 # Tests that the internals in mono/io-layer/messages.c are ok by triggering the 
@@ -1159,12 +1207,12 @@ test_messages: w32message.exe
 	> test_messages.zero
 	$(JITTEST_PROG_RUN) w32message.exe >& w32message.allout && cmp test_messages.zero w32message.allout
 
-@INSTALL_2_1_TRUE@test_2_1 : test-coreclr-security
-@INSTALL_2_1_FALSE@test_2_1 :
+@MOONLIGHT_TRUE@test_2_1 : test-coreclr-security
+@MOONLIGHT_FALSE@test_2_1 :
 
 # test_messages fails on the buildbots
 #test: assemblyresolve/test/asm.dll testjit test-type-load test-generic-sharing test_platform test_2_1 test_messages
-test: assemblyresolve/test/asm.dll testjit test-type-load test-generic-sharing test_platform test-runtime-invoke test_2_1
+test: assemblyresolve/test/asm.dll testjit test-type-load test-generic-sharing test_platform test-runtime-invoke test-imt-big-iface test_2_1 test-process-exit
 
 assemblyresolve/test/asm.dll:
 	$(MAKE) -C assemblyresolve prereq
@@ -1211,7 +1259,7 @@ runtest: $(TESTSI_CS) $(TESTSI_IL) $(TESTBS) libtest.la $(PREREQSI_IL) $(PREREQS
 	failed_tests="";\
 	for i in $(TESTSI_CS) $(TESTBS) $(TESTSI_IL); do	\
 		rm -f $${i}.so; \
-		if [ x$(AOT) = x1 ]; then if echo $(AOT_DISABLED_TESTS) | grep -v -q $${i}; then $(with_mono_path) $(JITTEST_PROG_RUN) --aot --debug $${i} > /dev/null || exit 1; fi; fi; \
+		if [ x$(AOT) = x1 ]; then if echo $(AOT_DISABLED_TESTS) | grep -v -q $${i}; then $(with_mono_path) $(JITTEST_PROG_RUN) --aot --debug $${i} > $${i}.aotlog 2>&1 || exit 1; fi; fi; \
 		if $(srcdir)/test-driver '$(with_mono_path) $(JITTEST_PROG_RUN)' $$i '$(DISABLED_TESTS)' $(RUNTIME_ARGS); \
 		then \
 			passed=`expr $${passed} + 1`; \
@@ -1229,7 +1277,7 @@ runtest-managed: test-runner.exe $(TESTSI_CS) $(TESTSI_IL) $(TESTBS) libtest.la 
 	@$(RUNTIME) ./test-runner.exe -j a --disabled '$(DISABLED_TESTS)' $(TESTSI_CS) $(TESTBS) $(TESTSI_IL)
 
 testjit:
-	@$(MAKE) runtest
+	@if test x$(M) != x; then $(MAKE) runtest-managed; else $(MAKE) runtest; fi
 
 testaot:
 	@$(MAKE) AOT=1 runtest
@@ -1286,6 +1334,11 @@ test-runtime-invoke: TestDriver.dll gen-runtime-invoke.exe
 	@$(MCS) -out:runtime-invoke.gen.exe -r:TestDriver.dll runtime-invoke.gen.cs
 	@echo "Testing runtime-invoke.gen.exe..."
 	@$(RUNTIME) runtime-invoke.gen.exe > runtime-invoke.gen.exe.stdout 2> runtime-invoke.gen.exe.stderr
+test-imt-big-iface: TestDriver.dll make-imt-test.exe
+	@$(RUNTIME) make-imt-test.exe > imt_big_iface_test.cs
+	@$(MCS) -out:imt_big_iface_test.exe -r:TestDriver.dll imt_big_iface_test.cs
+	@echo "Testing imt_big_iface_test.exe..."
+	@$(RUNTIME) imt_big_iface_test.exe > imt_big_iface_test.exe.stdout 2> imt_big_iface_test.exe.stderr
 test-inline-call-stack-library.dll: TestDriver.dll $(srcdir)/test-inline-call-stack-library.cs
 	$(MCS) -t:library -out:test-inline-call-stack-library.dll $(srcdir)/test-inline-call-stack-library.cs
 test-inline-call-stack.exe: TestDriver.dll test-inline-call-stack-library.dll $(srcdir)/test-inline-call-stack.cs
@@ -1328,6 +1381,7 @@ bug-81691.exe bug-81691-b.dll: $(srcdir)/bug-81691.cs $(srcdir)/bug-81691-a.cs $
 	$(MCS) -target:library -out:bug-81691-b.dll -r:bug-81691-a.dll $(srcdir)/bug-81691-b.cs
 	$(MCS) -r:bug-81691-b.dll -out:bug-81691.exe $(srcdir)/bug-81691.cs
 	rm -f bug-81691-a.dll
+bug-81691.exe: bug-81691-b.dll
 bug-81466-lib.dll: bug-81466-lib.il
 	$(ILASM) /dll /output:bug-81466-lib.dll $(srcdir)/bug-81466-lib.il
 bug-81466.exe: bug-81466.il bug-81466-lib.dll
@@ -1336,8 +1390,6 @@ bug-324535-il.dll : bug-324535-il.il
 	$(ILASM) /dll /output:bug-324535-il.dll $(srcdir)/bug-324535-il.il
 bug-324535.exe : bug-324535.cs bug-324535-il.dll
 	$(MCS) -r:bug-324535-il.dll -out:bug-324535.exe $(srcdir)/bug-324535.cs
-imt_big_iface_test.cs: $(srcdir)/make_imt_test.sh
-	$(srcdir)/make_imt_test.sh > imt_big_iface_test.cs
 custom-modifiers-lib.dll: custom-modifiers-lib.il
 	$(ILASM) /dll /output:custom-modifiers-lib.dll $(srcdir)/custom-modifiers-lib.il
 custom-modifiers.2.exe: custom-modifiers.2.cs custom-modifiers-lib.dll
@@ -1347,12 +1399,12 @@ bug-382986-lib.dll: bug-382986-lib.cs
 bug-382986.exe: bug-382986.cs bug-382986-lib.dll
 	$(MCS) -out:$@ -r:bug-382986-lib.dll $(srcdir)/bug-382986.cs
 
-@INSTALL_2_1_TRUE@coreclr-security.exe : coreclr-security.cs
-@INSTALL_2_1_TRUE@	$(SMCS) -out:coreclr-security.exe $(srcdir)/coreclr-security.cs
+@MOONLIGHT_TRUE@coreclr-security.exe : coreclr-security.cs
+@MOONLIGHT_TRUE@	$(SMCS) -out:coreclr-security.exe $(srcdir)/coreclr-security.cs
 
-@INSTALL_2_1_TRUE@test-coreclr-security : coreclr-security.exe
-@INSTALL_2_1_TRUE@	@echo "Testing coreclr-security.exe..."
-@INSTALL_2_1_TRUE@	@$(RUNTIME21) --security=core-clr-test coreclr-security.exe
+@MOONLIGHT_TRUE@test-coreclr-security : coreclr-security.exe
+@MOONLIGHT_TRUE@	@echo "Testing coreclr-security.exe..."
+@MOONLIGHT_TRUE@	@$(RUNTIME_MOONLIGHT) --security=core-clr-test coreclr-security.exe
 generic-unboxing.2.dll : generic-unboxing.2.il
 	$(ILASM) /dll /output:generic-unboxing.2.dll $(srcdir)/generic-unboxing.2.il
 generic-boxing.2.dll : generic-boxing.2.il generic-unboxing.2.dll
@@ -1371,31 +1423,7 @@ gshared: test-generic-sharing
 gshared-aot:
 	@$(MAKE) AOT=1 gshared
 
-test-generic-sharing : generics-sharing.2.exe shared-generic-methods.2.exe	\
-		shared-generic-synchronized.2.exe generic-initobj.2.exe		\
-		generics-sharing-other-exc.2.exe generic-box.2.exe		\
-		generic-unbox.2.exe generic-delegate.2.exe generic-sizeof.2.exe	\
-		generic-ldobj.2.exe generic-mkrefany.2.exe			\
-		generic-refanyval.2.exe generic-ldtoken.2.exe			\
-		generic-ldtoken-method.2.exe  generic-ldtoken-field.2.exe	\
-		generic-virtual.2.exe generic-tailcall.2.exe			\
-		generic-interface-methods.2.exe generic-array-type.2.exe	\
-		generic-method-patching.2.exe generic-static-methods.2.exe	\
-		generic-null-call.2.exe generic-tailcall2.2.exe			\
-		generic-array-exc.2.exe generic-special.2.exe			\
-		generic-exceptions.2.exe generic-delegate2.2.exe		\
-		generic-virtual2.2.exe generic-valuetype-interface.2.exe	\
-		generic-valuetype-newobj.2.exe generic-valuetype-newobj2.2.exe	\
-		generic-getgenericarguments.2.exe generic-type-builder.2.exe	\
-		generic-synchronized.2.exe generic-delegate-ctor.2.exe		\
-		generic-constrained.2.exe bug-431413.2.exe			\
-		generic-virtual-invoke.2.exe generic-typedef.2.exe		\
-		generic-marshalbyref.2.exe bug-459285.2.exe bug-461198.2.exe	\
-		generic-sealed-virtual.2.exe generic-system-arrays.2.exe	\
-		generic-stack-traces.2.exe generic-stack-traces2.2.exe		\
-		bug-472600.2.exe bug-473482.2.exe bug-473999.2.exe		\
-		bug-479763.2.exe generic-xdomain.2.exe				\
-		generic-type-load-exception.2.exe bug-616463.exe
+test-generic-sharing-normal: $(GSHARED_TESTS)
 	@for fn in $+ ; do	\
 		echo "Testing $$fn ...";	\
 		MONO_GENERIC_SHARING=all $(RUNTIME) -O=gshared                $$fn > $$fn.stdout || exit 1;	\
@@ -1404,6 +1432,12 @@ test-generic-sharing : generics-sharing.2.exe shared-generic-methods.2.exe	\
 		MONO_GENERIC_SHARING=all $(RUNTIME) -O=gshared,-inline,shared $$fn > $fn.stdout || exit 1;	\
 		if [ x$(AOT) = x1 ]; then MONO_GENERIC_SHARING=all $(with_mono_path) $(JITTEST_PROG_RUN) --aot --debug $$fn > /dev/null || exit 1; MONO_GENERIC_SHARING=all $(RUNTIME) $$fn > $$fn.stdout || exit 1; fi; \
 	done
+
+test-generic-sharing-managed: test-runner.exe $(GSHARED_TESTS)
+	@$(RUNTIME) ./test-runner.exe -j a --opt-sets "gshared gshared,shared gshared,-inline gshared,-inline,shared" $(GSHARED_TESTS)
+
+test-generic-sharing:
+	@if test x$(M) != x; then $(MAKE) test-generic-sharing-managed; else $(MAKE) test-generic-sharing-normal; fi
 async-exceptions.exe : async-exceptions.cs
 	$(MCS) -out:async-exceptions.exe $(srcdir)/async-exceptions.cs
 test-async-exceptions : async-exceptions.exe
@@ -1411,7 +1445,7 @@ test-async-exceptions : async-exceptions.exe
 	for i in `echo 0 1 2 3 4 5 6 7 8 9 10`; do $(RUNTIME) --inject-async-exc Tests:bar $$i async-exceptions.exe || exit 1; done
 modules-m1.netmodule: modules-m1.cs
 	$(MCS) -out:$@ /target:module $(srcdir)/modules-m1.cs
-modules.exe: modules.cs modules-m1.netmodule
+modules.exe: modules.cs modules-m1.netmodule TestDriver.dll
 	$(MCS) -out:$@ /addmodule:modules-m1.netmodule -r:TestDriver.dll $(srcdir)/modules.cs
 
 # Useful if mono is compiled with --enable-shared=no
@@ -1420,6 +1454,11 @@ patch-libtool:
 	sed -e 's,build_libtool_libs=no,build_libtool_libs=yes,g' libtool > 2; mv 2 libtool
 	sed -e 's,LIBTOOL =,LIBTOOL2 =,g' Makefile > 2 && echo "LIBTOOL = bash ./libtool" > 1 && cat 1 2 > Makefile
 	touch libtest.c
+test-process-exit:
+	@$(MCS) $(srcdir)/bug-438454.cs -out:bug-438454.exe
+	@echo "Testing bug-438454.exe..."
+	@$(RUNTIME) bug-438454.exe > bug-438454.exe.stdout
+	@diff bug-438454.exe.stdout $(srcdir)/bug-438454.exe.stdout.expected
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
